apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookfinder.fullname" . }}-config
  labels:
    {{- include "bookfinder.labels" . | nindent 4 }}
data:
  BACKEND_URL: "http://{{ .Values.backend.name }}:{{ .Values.backend.service.port }}"
