apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- include "bookfinder.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      {{- include "bookfinder.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  replicas: {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "bookfinder.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "bookfinder.fullname" . }}-config
              key: BACKEND_URL
        volumeMounts:
        - name: streamlit-secrets
          mountPath: /app/.streamlit/secrets.toml
          subPath: secrets.toml
          readOnly: true
      volumes:
      - name: streamlit-secrets
        secret:
          secretName: {{ include "bookfinder.fullname" . }}-secrets