apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookfinder.fullname" . }}-secrets
  labels:
    {{- include "bookfinder.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.toml: |
    [google_books_api_key]
    key = "{{ .Values.googleBooksApiKey | default "AIzaSyDlaj5CJnliwC10ZzkDAWRGB-erfzEcHCE" }}"