apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookfinder-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bookfinder.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: book-finder-frontend
            port:
              number: 80
